# Generated by Django 6.0.3 on 2026-03-28 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('org', models.CharField(blank=True, max_length=500, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('sector', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('marketAvg', models.FloatField(blank=True, null=True)),
                ('companyAgeMonths', models.IntegerField(blank=True, null=True)),
                ('sameAddress', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('riskLevel', models.CharField(default='low', max_length=20)),
                ('riskLabel', models.CharField(default='Past Xavf', max_length=50)),
                ('riskColor', models.CharField(default='#4caf50', max_length=20)),
                ('factors', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('inn', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(default='company', max_length=50)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('ageMonths', models.IntegerField(blank=True, null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.tender')),
            ],
        ),
    ]
